import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import SplitType from 'split-type'

// let text = new SplitType('#text');
//         let characters = document.querySelectorAll('.char');
        
//         for(i=0; i<characters.length; i++){
//           characters[i].classListadd('translate-y-full');
//         }
        
//         gsap.to('.char', {
//            y: 0,
//            stagger:  0.05,
//            delay: 0.02,
//            duration: 0.5 
//         });
        


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      
      
      <div className="md:min-h-screen h-96 hero justify-end " style={{ backgroundImage: `url("/images/justice.jpg")` }}>
        <div className="hero object-cover"></div>
        <div className="text-end text-neutral-content ">
          <div className="justify-end md:pr-10 md:mr-10 m-2">
            <h1 className="mb-5 md:text-7xl text-5xl font-bold">Big Ideas </h1>
            <h1 className="mb-5 md:text-7xl text-5xl font-bold">Creative Thinkings</h1>
            <h1 className="mb-5 md:text-7xl text-5xl font-bold">Driven By Technology</h1>
            <button className="btn btn-primary">Learn More</button>
          </div>
        </div>
      </div>
      
      
    </div>
    
  )
}
