import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'


import Testimonials from '@/components/Testimonials'
import Domainnews from '@/pages/Domainnews'


// let text = new SplitType('#text');
//         let characters = document.querySelectorAll('.char');
        
//         for(i=0; i<characters.length; i++){
//           characters[i].classListadd('translate-y-full');
//         }
        
//         gsap.to('.char', {
//            y: 0,
//            stagger:  0.05,
//            delay: 0.02,
//            duration: 0.5 
//         });
        


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>   
      
      
      <div className="justify-end md:min-h-screen h-96 hero " style={{ backgroundImage: `url("/images/justice.jpg")` }}>
        <div className="object-cover hero"></div>
        <div className="text-end text-neutral-content ">
          <div className="justify-end m-2 md:pr-10 md:mr-10">
            <h1 className="mb-5 text-5xl font-bold md:text-7xl">Big Ideas </h1>
            <h1 className="mb-5 text-5xl font-bold md:text-7xl">Creative Thinkings</h1>
            <h1 className="mb-5 text-5xl font-bold md:text-7xl">Driven By Technology</h1>
            <button className="btn btn-active btn-primary">Learn More</button>
          </div>
        </div>
      </div>
      
      <Testimonials />
      <div className="stats shadow">
  
  <div className="stat">
    <div className="stat-figure text-primary">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-8 h-8 stroke-current"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"></path></svg>
    </div>
    <div className="stat-title">Total Likes</div>
    <div className="stat-value text-primary">25.6K</div>
    <div className="stat-desc">21% more than last month</div>
  </div>
  
  <div className="stat">
    <div className="stat-figure text-secondary">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" className="inline-block w-8 h-8 stroke-current"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path></svg>
    </div>
    <div className="stat-title">Page Views</div>
    <div className="stat-value text-secondary">2.6M</div>
    <div className="stat-desc">21% more than last month</div>
  </div>
  
  <div className="stat">
    <div className="stat-figure text-secondary">
      <div className="avatar online">
        <div className="w-16 rounded-full">
          <img src="/images/img.jpg" />
        </div>
      </div>
    </div>
    <div className="stat-value">86%</div>
    <div className="stat-title">Tasks done</div>
    <div className="stat-desc text-secondary">31 tasks remaining</div>
  </div>
  
</div>
      
    </div>
    
    
  )
}
